// export const TOUR_VERSION = 0; // bump to reset tour for all users

export const STEPS = [
  {
    refKey: null,
    tab: "Home",
    side: "center",
    emoji: "👋",
    title: "Let's take a quick tour!",
    body: "I'll show you what each part of the app does. Takes about 20 seconds.",
  },
  {
    refKey: "home_calories",
    tab: "Home",
    side: "bottom",
    emoji: "🔥",
    title: "Calorie ring",
    body: "The ring fills as you eat. Tap Log a Meal to add food and track your macros.",
  },
  {
    refKey: "home_workout",
    tab: "Home",
    side: "bottom",
    emoji: "💪",
    title: "Your workout",
    body: "Tap ▶ to start your session. Sets and reps log automatically.",
  },
  {
    refKey: "home_water",
    tab: "Home",
    side: "bottom",
    emoji: "💧",
    title: "Water · Steps · Sleep",
    body: "Tap +250ml to log water. These all affect your recovery score.",
  },
  {
    refKey: "home_recovery",
    tab: "Home",
    side: "top",
    emoji: "📊",
    title: "Recovery score",
    body: "🟢 Push hard · 🟠 Moderate · 🔴 Rest. Check this every morning.",
  },
  {
    refKey: "home_week",
    tab: "Home",
    side: "top",
    emoji: "📅",
    title: "Weekly streak",
    body: "Each dot = a training day. Consistency beats any single perfect session.",
  },
  {
    refKey: null,
    tab: "Training",
    side: "center",
    emoji: "🏋️",
    title: "Training tab",
    body: "Your full AI-generated workout split. Every exercise picked for your exact goal and equipment.",
  },
  {
    refKey: null,
    tab: "Nutrition",
    side: "center",
    emoji: "🥗",
    title: "Nutrition tab",
    body: "Log meals, scan barcodes, hit your daily targets. Protein first, everything else second.",
  },
  {
    refKey: null,
    tab: "PostureAI",
    side: "center",
    emoji: "📸",
    title: "PostureAI tab",
    body: "Camera-based posture scan. Do it weekly — most injuries start with bad form.",
  },
  {
    refKey: "yara_fab",
    tab: "Home",
    side: "top",
    emoji: "👩‍⚕️",
    title: "Alexi — your AI coach",
    body: "Tap anytime for advice. Alexi knows your whole profile and never asks you twice.",
  },
  {
    refKey: null,
    tab: "Home",
    side: "center",
    emoji: "🚀",
    title: "You're all set!",
    body: "Your plan is built, Alexi is ready, and your progress starts now.",
  },
];